#!/usr/bin/env python
"""Usage: choose (merger|reviewer) [PROJECT] [--noob] [--not NAME...]

Project defaults to nengo.

Examples
--------
choose merger
    Chooses a merger among nengo experts.
choose reviewer nengo_ocl --noob
    Chooses a reviewer among nengo_ocl non-experts.

See man choose for more information.
"""

import argparse
import json
import os.path
import random
import sys


if __name__ != '__main__':
    raise ImportError("Don't import me, bro!")


roles = ["merger", "reviewer"]
projects = ["nengo", "nengo_gui", "nengo_ocl"]

# Process command line args
parser = argparse.ArgumentParser()
parser.add_argument('role', type=str)
parser.add_argument('project', type=str, nargs='?', default="nengo")
parser.add_argument('--noob', dest='expert', action='store_const',
                    const=False, default=True)
parser.add_argument('--not', dest='exclude', nargs='+', default=[])
args = parser.parse_args()

role = args.role
project = args.project
expert = args.expert

if role not in roles:
    sys.exit(__doc__)

if project not in projects:
    print("%s not recognized. Including all contributors." % project)
    project = None

# Read contributors.json into a list
contrib_f = os.path.join(os.path.dirname(__file__), "contributors.json")
with open(contrib_f, 'r') as fp:
    contribs = json.load(fp)

# Filter list based on role and expertise
contribs = [contrib for contrib in contribs
            if contrib[role] and (project in contrib["expertise"]) == expert]

# Exclude any specified names
for name in args.exclude:
    contribs = [contrib for contrib in contribs
                if name not in contrib["name"].lower()]

# Can we choose someone?
if len(contribs) == 0:
    print("Sorry, no one meets that description! Relax your requirements.")
else:
    # Choose someone!
    contrib = random.choice(contribs)
    print("The lucky %s is %s!\nIf that doesn't work, run this again." % (
        role, contrib["name"]))
